version: '1.0'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}